// <auto-generated />
using System;
using GlavnayaKniga.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlavnayaKniga.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullCode")
                        .HasColumnType("text")
                        .HasColumnName("full_code");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsSynthetic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_synthetic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_accounts_code");

                    b.HasIndex("FullCode")
                        .HasDatabaseName("i_x_accounts_full_code");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("i_x_accounts_is_archived");

                    b.HasIndex("IsSynthetic")
                        .HasDatabaseName("i_x_accounts_is_synthetic");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("i_x_accounts_parent_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_x_accounts_type");

                    b.HasIndex("Code", "IsArchived")
                        .IsUnique()
                        .HasDatabaseName("i_x_accounts_code_is_archived")
                        .HasFilter("\"is_archived\" = false");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_type_id");

                    b.Property<DateTime?>("CommissioningDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commissioning_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecommissioningDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decommissioning_date");

                    b.Property<decimal?>("InitialCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("initial_cost");

                    b.Property<string>("InventoryNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inventory_number");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_number");

                    b.Property<decimal?>("ResidualValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("residual_value");

                    b.Property<int?>("ResponsiblePersonId")
                        .HasColumnType("integer")
                        .HasColumnName("responsible_person_id");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YearOfManufacture")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_manufacture");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_assets_account_id");

                    b.HasIndex("AssetTypeId")
                        .HasDatabaseName("i_x_assets_asset_type_id");

                    b.HasIndex("InventoryNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_assets_inventory_number")
                        .HasFilter("\"inventory_number\" IS NOT NULL");

                    b.HasIndex("RegistrationNumber")
                        .HasDatabaseName("i_x_assets_registration_number");

                    b.HasIndex("ResponsiblePersonId")
                        .HasDatabaseName("i_x_assets_responsible_person_id");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("i_x_assets_serial_number");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_asset_types_name");

                    b.ToTable("asset_types");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_number");

                    b.Property<string>("BIK")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("b_i_k");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_date");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("close_reason");

                    b.Property<string>("CorrespondentAccount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("correspondent_account");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("RUB")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_date");

                    b.Property<int>("SubaccountId")
                        .HasColumnType("integer")
                        .HasColumnName("subaccount_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_bank_accounts_account_number");

                    b.HasIndex("SubaccountId")
                        .HasDatabaseName("i_x_bank_accounts_subaccount_id");

                    b.ToTable("bank_accounts");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.BankStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_number");

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_account_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("ImportedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("imported_by");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("i_x_bank_statements_bank_account_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_bank_statements_status");

                    b.HasIndex("AccountNumber", "StartDate", "EndDate")
                        .HasDatabaseName("i_x_bank_statements_account_number_start_date_end_date");

                    b.ToTable("bank_statements");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.BankStatementDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BankStatementId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_statement_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<int?>("EntryId")
                        .HasColumnType("integer")
                        .HasColumnName("entry_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<string>("PayerAccount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payer_account");

                    b.Property<string>("PayerBIK")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payer_b_i_k");

                    b.Property<int?>("PayerCounterpartyId")
                        .HasColumnType("integer")
                        .HasColumnName("payer_counterparty_id");

                    b.Property<string>("PayerINN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payer_i_n_n");

                    b.Property<string>("PayerName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("payer_name");

                    b.Property<string>("PaymentPurpose")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("payment_purpose");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_type");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_date");

                    b.Property<string>("RecipientAccount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("recipient_account");

                    b.Property<string>("RecipientBIK")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recipient_b_i_k");

                    b.Property<int?>("RecipientCounterpartyId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_counterparty_id");

                    b.Property<string>("RecipientINN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recipient_i_n_n");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recipient_name");

                    b.Property<DateTime?>("WithdrawnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_date");

                    b.HasKey("Id");

                    b.HasIndex("BankStatementId")
                        .HasDatabaseName("i_x_bank_statement_documents_bank_statement_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("i_x_bank_statement_documents_date");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("i_x_bank_statement_documents_entry_id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("i_x_bank_statement_documents_hash");

                    b.HasIndex("PayerCounterpartyId")
                        .HasDatabaseName("i_x_bank_statement_documents_payer_counterparty_id");

                    b.HasIndex("RecipientCounterpartyId")
                        .HasDatabaseName("i_x_bank_statement_documents_recipient_counterparty_id");

                    b.HasIndex("PayerAccount", "RecipientAccount")
                        .HasDatabaseName("i_x_bank_statement_documents_payer_account_recipient_account");

                    b.ToTable("bank_statement_documents");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Counterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("actual_address");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("full_name");

                    b.Property<string>("INN")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("i_n_n");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("KPP")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("k_p_p");

                    b.Property<string>("LegalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("legal_address");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("OGRN")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("o_g_r_n");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("short_name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("INN")
                        .IsUnique()
                        .HasDatabaseName("i_x_counterpartys_i_n_n")
                        .HasFilter("\"i_n_n\" IS NOT NULL AND \"i_n_n\" != ''");

                    b.HasIndex("ShortName", "IsArchived")
                        .HasDatabaseName("i_x_counterpartys_short_name_is_archived");

                    b.ToTable("counterpartys");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.CounterpartyBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_number");

                    b.Property<string>("BIK")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("b_i_k");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_name");

                    b.Property<string>("CorrespondentAccount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("correspondent_account");

                    b.Property<int>("CounterpartyId")
                        .HasColumnType("integer")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("RUB")
                        .HasColumnName("currency");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .HasDatabaseName("i_x_counterparty_bank_accounts_account_number");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("i_x_counterparty_bank_accounts_counterparty_id");

                    b.ToTable("counterparty_bank_accounts");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("full_name");

                    b.Property<int?>("HeadEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("head_employee_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_departments_code");

                    b.HasIndex("HeadEmployeeId")
                        .HasDatabaseName("i_x_departments_head_employee_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_departments_name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("i_x_departments_parent_id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentPositionId")
                        .HasColumnType("integer")
                        .HasColumnName("current_position_id");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<DateTime?>("DismissalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissal_date");

                    b.Property<DateTime?>("DismissalOrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissal_order_date");

                    b.Property<string>("DismissalOrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dismissal_order_number");

                    b.Property<string>("DismissalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dismissal_reason");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<DateTime?>("HireOrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_order_date");

                    b.Property<string>("HireOrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hire_order_number");

                    b.Property<int>("IndividualId")
                        .HasColumnType("integer")
                        .HasColumnName("individual_id");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("personnel_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("work_email");

                    b.Property<string>("WorkPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("work_phone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPositionId")
                        .HasDatabaseName("i_x_employees_current_position_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("i_x_employees_department_id");

                    b.HasIndex("DismissalDate")
                        .HasDatabaseName("i_x_employees_dismissal_date");

                    b.HasIndex("HireDate")
                        .HasDatabaseName("i_x_employees_hire_date");

                    b.HasIndex("IndividualId")
                        .HasDatabaseName("i_x_employees_individual_id");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("i_x_employees_manager_id");

                    b.HasIndex("PersonnelNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_employees_personnel_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_employees_status");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.EmploymentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("change_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType")
                        .HasDatabaseName("i_x_employment_historys_change_type");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("i_x_employment_historys_employee_id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("i_x_employment_historys_end_date");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("i_x_employment_historys_position_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("i_x_employment_historys_start_date");

                    b.ToTable("employment_historys");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BasisId")
                        .HasColumnType("integer")
                        .HasColumnName("basis_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("credit_account_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("DebitAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("debit_account_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("receipt_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BasisId")
                        .HasDatabaseName("i_x_entries_basis_id");

                    b.HasIndex("CreditAccountId")
                        .HasDatabaseName("i_x_entries_credit_account_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("i_x_entries_date");

                    b.HasIndex("DebitAccountId")
                        .HasDatabaseName("i_x_entries_debit_account_id");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("i_x_entries_receipt_id");

                    b.ToTable("entries");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("actual_address");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("birth_place");

                    b.Property<string>("Citizenship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("citizenship");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("INN")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("i_n_n");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("PassportDepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("passport_department_code");

                    b.Property<DateTime?>("PassportIssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("passport_issue_date");

                    b.Property<string>("PassportIssuedBy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passport_issued_by");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("passport_number");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("passport_series");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("registration_address");

                    b.Property<string>("SNILS")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("s_n_i_l_s");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("INN")
                        .IsUnique()
                        .HasDatabaseName("i_x_individuals_i_n_n")
                        .HasFilter("\"i_n_n\" IS NOT NULL AND \"i_n_n\" != ''");

                    b.HasIndex("SNILS")
                        .IsUnique()
                        .HasDatabaseName("i_x_individuals_s_n_i_l_s")
                        .HasFilter("\"s_n_i_l_s\" IS NOT NULL AND \"s_n_i_l_s\" != ''");

                    b.HasIndex("LastName", "FirstName", "MiddleName", "BirthDate")
                        .HasDatabaseName("i_x_individuals_last_name_first_name_middle_name_birth_date");

                    b.ToTable("individuals");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Nomenclature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Article")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("article");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentStock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("current_stock");

                    b.Property<int>("DefaultVatAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("default_vat_account_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("FullName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<decimal?>("MaxStock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("max_stock");

                    b.Property<decimal?>("MinStock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("min_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("purchase_price");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sale_price");

                    b.Property<int?>("StorageLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("storage_location_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_nomenclatures_account_id");

                    b.HasIndex("Article")
                        .IsUnique()
                        .HasDatabaseName("i_x_nomenclatures_article");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("i_x_nomenclatures_barcode");

                    b.HasIndex("DefaultVatAccountId")
                        .HasDatabaseName("i_x_nomenclatures_default_vat_account_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_nomenclatures_name");

                    b.HasIndex("StorageLocationId")
                        .HasDatabaseName("i_x_nomenclatures_storage_location_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_x_nomenclatures_type");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("i_x_nomenclatures_unit_id");

                    b.ToTable("nomenclatures");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<decimal?>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_salary");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("EducationRequirements")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("education_requirements");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("short_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_positions_name");

                    b.ToTable("positions");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accounting_date");

                    b.Property<string>("Basis")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("basis");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contract_date");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_number");

                    b.Property<int>("ContractorId")
                        .HasColumnType("integer")
                        .HasColumnName("contractor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("CreditAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("credit_account_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsUPD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_u_p_d");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("PostedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("posted_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal?>("TotalAmountWithVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount_with_vat");

                    b.Property<decimal?>("TotalVatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_vat_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VatCalculationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("vat_calculation_method");

                    b.HasKey("Id");

                    b.HasIndex("AccountingDate")
                        .HasDatabaseName("i_x_receipts_accounting_date");

                    b.HasIndex("ContractorId")
                        .HasDatabaseName("i_x_receipts_contractor_id");

                    b.HasIndex("CreditAccountId")
                        .HasDatabaseName("i_x_receipts_credit_account_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("i_x_receipts_date");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("i_x_receipts_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_receipts_status");

                    b.ToTable("receipts");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.ReceiptItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("AmountWithVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_with_vat");

                    b.Property<int>("DebitAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("debit_account_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer")
                        .HasColumnName("nomenclature_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("receipt_id");

                    b.Property<int?>("StorageLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("storage_location_id");

                    b.Property<int>("VatAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("vat_account_id");

                    b.Property<decimal?>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vat_amount");

                    b.Property<decimal?>("VatRate")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("DebitAccountId")
                        .HasDatabaseName("i_x_receipt_items_debit_account_id");

                    b.HasIndex("NomenclatureId")
                        .HasDatabaseName("i_x_receipt_items_nomenclature_id");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("i_x_receipt_items_receipt_id");

                    b.HasIndex("StorageLocationId")
                        .HasDatabaseName("i_x_receipt_items_storage_location_id");

                    b.HasIndex("VatAccountId")
                        .HasDatabaseName("i_x_receipt_items_vat_account_id");

                    b.ToTable("receipt_items");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.StorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<decimal?>("Area")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("area");

                    b.Property<decimal?>("Capacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int?>("ResponsibleEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("responsible_employee_id");

                    b.Property<string>("TemperatureRegime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("temperature_regime");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_storage_locations_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_storage_locations_name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("i_x_storage_locations_parent_id");

                    b.HasIndex("ResponsibleEmployeeId")
                        .HasDatabaseName("i_x_storage_locations_responsible_employee_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_x_storage_locations_type");

                    b.ToTable("storage_locations");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.TransactionBasis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_transaction_bases_name");

                    b.ToTable("transaction_bases");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("InternationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("international_code");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("short_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_units_of_measure_code");

                    b.HasIndex("ShortName")
                        .HasDatabaseName("i_x_units_of_measure_short_name");

                    b.ToTable("units_of_measure");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Account", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Asset", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Counterparty", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("AssetType");

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "Subaccount")
                        .WithMany()
                        .HasForeignKey("SubaccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subaccount");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.BankStatement", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.BankStatementDocument", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.BankStatement", "BankStatement")
                        .WithMany("Documents")
                        .HasForeignKey("BankStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GlavnayaKniga.Domain.Entities.Counterparty", "PayerCounterparty")
                        .WithMany()
                        .HasForeignKey("PayerCounterpartyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GlavnayaKniga.Domain.Entities.Counterparty", "RecipientCounterparty")
                        .WithMany()
                        .HasForeignKey("RecipientCounterpartyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BankStatement");

                    b.Navigation("Entry");

                    b.Navigation("PayerCounterparty");

                    b.Navigation("RecipientCounterparty");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.CounterpartyBankAccount", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Counterparty", "Counterparty")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Department", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Employee", "HeadEmployee")
                        .WithMany()
                        .HasForeignKey("HeadEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Departments_Employees_HeadEmployeeId");

                    b.HasOne("GlavnayaKniga.Domain.Entities.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Departments_Departments_ParentId");

                    b.Navigation("HeadEmployee");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Employee", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Position", "CurrentPosition")
                        .WithMany("Employees")
                        .HasForeignKey("CurrentPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Employees_Departments_DepartmentId");

                    b.HasOne("GlavnayaKniga.Domain.Entities.Individual", "Individual")
                        .WithMany()
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentPosition");

                    b.Navigation("Department");

                    b.Navigation("Individual");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.EmploymentHistory", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Employee", "Employee")
                        .WithMany("EmploymentHistory")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Position", "Position")
                        .WithMany("EmploymentHistory")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Entry", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.TransactionBasis", "Basis")
                        .WithMany("Entries")
                        .HasForeignKey("BasisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "CreditAccount")
                        .WithMany("CreditEntries")
                        .HasForeignKey("CreditAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "DebitAccount")
                        .WithMany("DebitEntries")
                        .HasForeignKey("DebitAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Receipt", null)
                        .WithMany("Entries")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Basis");

                    b.Navigation("CreditAccount");

                    b.Navigation("DebitAccount");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Nomenclature", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "DefaultVatAccount")
                        .WithMany()
                        .HasForeignKey("DefaultVatAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GlavnayaKniga.Domain.Entities.UnitOfMeasure", "Unit")
                        .WithMany("Nomenclatures")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("DefaultVatAccount");

                    b.Navigation("StorageLocation");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Receipt", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Counterparty", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "CreditAccount")
                        .WithMany()
                        .HasForeignKey("CreditAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("CreditAccount");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.ReceiptItem", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "DebitAccount")
                        .WithMany()
                        .HasForeignKey("DebitAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.Receipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlavnayaKniga.Domain.Entities.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GlavnayaKniga.Domain.Entities.Account", "VatAccount")
                        .WithMany()
                        .HasForeignKey("VatAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DebitAccount");

                    b.Navigation("Nomenclature");

                    b.Navigation("Receipt");

                    b.Navigation("StorageLocation");

                    b.Navigation("VatAccount");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.StorageLocation", b =>
                {
                    b.HasOne("GlavnayaKniga.Domain.Entities.StorageLocation", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GlavnayaKniga.Domain.Entities.Employee", "ResponsibleEmployee")
                        .WithMany()
                        .HasForeignKey("ResponsibleEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");

                    b.Navigation("ResponsibleEmployee");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Account", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("CreditEntries");

                    b.Navigation("DebitEntries");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.BankStatement", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Counterparty", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmploymentHistory");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("EmploymentHistory");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.Receipt", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.StorageLocation", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.TransactionBasis", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("GlavnayaKniga.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("Nomenclatures");
                });
#pragma warning restore 612, 618
        }
    }
}
